# Generated by Django 5.2 on 2025-04-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
