# Generated by Django 5.2 on 2025-04-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='employees/photos/'),
        ),
    ]
