# Generated by Django 5.2 on 2025-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('birthdate', models.DateField()),
                ('age', models.PositiveIntegerField(editable=False)),
                ('contact_number', models.CharField(max_length=20)),
                ('diagnosis', models.CharField(choices=[('Pending', 'Pending'), ('No Findings', 'No Findings'), ('PTB', 'PTB')], default='Pending', max_length=20)),
            ],
        ),
    ]
