# Generated by Django 5.2 on 2025-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=0, editable=False, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
