# Generated by Django 5.2 on 2025-04-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='confidence',
            field=models.FloatField(blank=True, help_text='Model confidence (0–1) for the last diagnosis', null=True),
        ),
    ]
