# Generated by Django 5.2 on 2025-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(choices=[('Pending', 'Pending'), ('No Findings', 'No Findings'), ('Cavity', 'Cavity'), ('Effusion', 'Effusion')], default='Pending', max_length=20),
        ),
    ]
