# Generated by Django 5.2 on 2025-04-27 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_patient_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('xray_image', models.ImageField(blank=True, help_text='The exact X-ray image used for this diagnosis.', null=True, upload_to='diagnosis_history/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patient.patient')),
            ],
            options={
                'ordering': ['-diagnosed_at'],
            },
        ),
    ]
